### ISSUE TITLE
Improve input fields for data

### ISSUE THREAD

**Issue by Camerooooon** [Camerooooon/lepto-classifier-frontend#9]
- [x] #10
- [x] #11
- [x] #12
- [x] #13
- [x] #14

If possible try to avoid Javascript unless absolutely necessary.

**Comment by abitsalihu** [comment]
Do you need to fix the UI of the input fields? I can work on this!

**Comment by Camerooooon** [comment]
> Do you need to fix the UI of the input fields? I can work on this!

Thank you for being interested in helping. I'm going to split this issue up into multiple small issues so we can work on this together.

I will edit my original message in a bit with a task list with specific issues soon.

**Comment by Camerooooon** [comment]
All done :partying_face:
